name: Firebase Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install

      - name: Crear archivo .env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "VITE_API_KEY=${{ secrets.VITE_API_KEY_PROD }}" >> .env
            echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN_PROD }}" >> .env
            echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID_PROD }}" >> .env
            echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET_PROD }}" >> .env
            echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID_PROD }}" >> .env
            echo "VITE_APP_ID=${{ secrets.VITE_APP_ID_PROD }}" >> .env
          else
            echo "VITE_API_KEY=${{ secrets.VITE_API_KEY_DEV }}" >> .env
            echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN_DEV }}" >> .env
            echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID_DEV }}" >> .env
            echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET_DEV }}" >> .env
            echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID_DEV }}" >> .env
            echo "VITE_APP_ID=${{ secrets.VITE_APP_ID_DEV }}" >> .env
          fi

      - name: Build del proyecto
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npm run build:production
          else
            npm run build:develop
          fi

      - name: Deploy a Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_SERVICE_ACCOUNT_PROD || secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
          projectId: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROJECT_ID_PROD || secrets.FIREBASE_PROJECT_ID_DEV }}
          target: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}
          channelId: 'live'
